# Generated by Django 5.1.1 on 2024-10-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_resource_video_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled', max_length=500),
        ),
    ]
