# Generated by Django 5.1.1 on 2024-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time_duration',
            field=models.FloatField(null=True),
        ),
    ]
