# Generated by Django 5.1.1 on 2024-10-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_time_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='position',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time_duration',
        ),
    ]
