# Generated by Django 5.1.1 on 2024-10-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_position_lesson_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='position',
            new_name='serial_number',
        ),
    ]
