# Generated by Django 5.1.1 on 2024-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_position_video_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='serial_number',
        ),
    ]
