# Generated by Django 5.1.2 on 2024-10-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_question_answer_quizzy_question_quizzy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzy',
            old_name='lession',
            new_name='lesson',
        ),
    ]
