# Generated by Django 5.1.1 on 2024-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
