# Generated by Django 5.1.2 on 2024-11-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzy',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='quizzy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quizzy'),
        ),
    ]
