# Generated by Django 5.1.1 on 2024-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_quizzy_score_alter_question_quizzy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzy',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
